Repository ruby/irb, pull requests merged in 2023-08, with the labels that each got.

#661 Add workspace category
  README.md
  lib/irb/cmd/chws.rb
  lib/irb/cmd/pushws.rb
Labels: enhancement

#654 Deprecate multi-irb commands
  README.md
  lib/irb/cmd/subirb.rb
Labels: enhancement

#652 Fix nested sessions' history saving
  lib/irb.rb
  lib/irb/context.rb
  lib/irb/history.rb
  lib/irb/input-method.rb
  test/irb/test_history.rb
Labels: bug

#676 Add black and white color to IRB::Color
  lib/irb/color.rb
Labels: enhancement

#669 Don't echo an expression's result when it ends with a semicolon
  lib/irb.rb
  test/irb/test_evaluation.rb
  test/irb/yamatanooroti/test_rendering.rb
Labels: enhancement

#679 Drop showing indent level number in DEFAULT prompt and INF_RUBY prompt
  lib/irb.rb
  lib/irb/init.rb
  test/irb/yamatanooroti/test_rendering.rb
Labels: enhancement

#575 Support seamless integration with ruby/debug
  lib/irb.rb
  lib/irb/cmd/debug.rb
  lib/irb/cmd/subirb.rb
  lib/irb/context.rb
  lib/irb/debug.rb
  lib/irb/debug/ui.rb
  lib/irb/history.rb
  lib/irb/ruby-lex.rb
  lib/irb/workspace.rb
  test/irb/test_debug_cmd.rb
  test/irb/test_history.rb
Labels: enhancement

#686 Support `VISUAL` env var, and prefer it over `EDITOR`
  README.md
  lib/irb/cmd/edit.rb
  test/irb/test_cmd.rb
Labels: enhancement

#692 Deprecate RubyLex and warn about referencing to it
  lib/irb/ruby-lex.rb
  test/irb/test_nesting_parser.rb
  test/irb/test_ruby_lex.rb
Labels: enhancement

#689 Add a debugging with IRB section to README
  README.md
Labels: documentation

#693 Improve help/show_cmds message during debugger integration
  lib/irb/cmd/show_cmds.rb
  lib/irb/statement.rb
  test/irb/test_debug_cmd.rb
Labels: enhancement

#673 Add a new readme section for IRB extension
  README.md
Labels: documentation

#704 Drop rdoc's version requirement
  irb.gemspec
Labels: bug
