Repository ruby/irb, pull requests merged in 2023-12, with the labels that each got.

#761 Implement `history` command
  README.md
  lib/irb/cmd/history.rb
  lib/irb/extend-command.rb
  test/irb/test_cmd.rb
Labels: enhancement

#797 Update Pry comparison doc's entries about history and pager support
  COMPARED_WITH_PRY.md
Labels: documentation

#800 Pager should be disabled when TERM=dumb
  lib/irb/pager.rb
Labels: bug

#806 Debugging command warning should not be specific to the `debug` command
  lib/irb/cmd/debug.rb
Labels: bug

#738 [DOC] RDoc for module IRB
  .document
  .gitignore
  doc/irb/indexes.rdoc
  lib/irb.rb
  lib/irb/context.rb
  lib/irb/help.rb
  lib/irb/xmp.rb
Labels: documentation

#811 Remove documents about deprecated/WIP features and some slight adjustments
  lib/irb.rb
Labels: documentation

#812 [DOC] Change indexes.rdoc to indexes.md
  .document
  doc/irb/indexes.md
  doc/irb/indexes.rdoc
  lib/irb.rb
Labels: documentation

#819 Remove dead doc
  lib/irb.rb
Labels: documentation

#820 Fix type completor section of README
  README.md
Labels: documentation
