Repository ruby/irb, pull requests merged in 2023-11, with the labels that each got.

#708 Type based completion using Prism and RBS
  Gemfile
  Rakefile
  lib/irb.rb
  lib/irb/cmd/irb_info.rb
  lib/irb/completion.rb
  lib/irb/context.rb
  lib/irb/init.rb
  lib/irb/input-method.rb
  lib/irb/type_completion/completor.rb
  lib/irb/type_completion/methods.rb
  lib/irb/type_completion/scope.rb
  lib/irb/type_completion/type_analyzer.rb
  lib/irb/type_completion/types.rb
  test/irb/test_cmd.rb
  test/irb/test_context.rb
  test/irb/test_input_method.rb
  test/irb/type_completion/test_scope.rb
  test/irb/type_completion/test_type_analyze.rb
  test/irb/type_completion/test_type_completor.rb
  test/irb/type_completion/test_types.rb
Labels: enhancement

#754 Add command line option to select which completor to use
  README.md
  lib/irb/init.rb
  lib/irb/lc/help-message
  lib/irb/lc/ja/help-message
  man/irb.1
  test/irb/test_init.rb
Labels: enhancement

#756 Improve the contributing guideline
  CONTRIBUTING.md
  README.md
Labels: documentation

#771 Enable completion setting through `IRB_COMPLETOR`
  README.md
  lib/irb/init.rb
  test/irb/test_init.rb
Labels: enhancement

#777 Rescue Exception, ignore warning in completion doc_namespace
  lib/irb/type_completion/completor.rb
Labels: bug

#768 Hint debugger command in `irb:rdbg` session
  lib/irb/debug.rb
  test/irb/yamatanooroti/test_rendering.rb
Labels: enhancement

#780 Handle handle_exception's exception
  lib/irb.rb
  test/irb/test_raise_exception.rb
Labels: bug

#782 Fix exception(backtrace=nil) prints nothing
  lib/irb.rb
  test/irb/test_raise_exception.rb
Labels: bug

#783 Support disabling pager
  lib/irb/init.rb
  lib/irb/lc/help-message
  lib/irb/pager.rb
  test/irb/test_cmd.rb
  test/irb/test_debug_cmd.rb
  test/irb/test_irb.rb
Labels: enhancement

#788 Display aliases in help message
  lib/irb/cmd/show_cmds.rb
  lib/irb/context.rb
  lib/irb/init.rb
  test/irb/test_cmd.rb
Labels: enhancement

#789 Hide debugger hint after the input is submitted
  lib/irb/debug.rb
  test/irb/yamatanooroti/test_rendering.rb
Labels: enhancement

#770 adding the -s flag to show_source
  lib/irb/cmd/show_source.rb
  lib/irb/source_finder.rb
  test/irb/test_cmd.rb
Labels: enhancement

#793 Change show_source tests into integration tests
  lib/irb/source_finder.rb
  test/irb/cmd/test_show_source.rb
  test/irb/test_cmd.rb
Labels: bug

#772 Split TypeCompletion to a gem
  Gemfile
  README.md
  Rakefile
  lib/irb/completion.rb
  lib/irb/context.rb
  lib/irb/type_completion/completor.rb
  lib/irb/type_completion/methods.rb
  lib/irb/type_completion/scope.rb
  lib/irb/type_completion/type_analyzer.rb
  lib/irb/type_completion/types.rb
  test/irb/test_context.rb
  test/irb/test_type_completor.rb
  test/irb/type_completion/test_scope.rb
  test/irb/type_completion/test_type_analyze.rb
  test/irb/type_completion/test_type_completor.rb
  test/irb/type_completion/test_types.rb
Labels: enhancement, Don't merge

#784 Page evaluation result's output
  lib/irb.rb
  lib/irb/pager.rb
  test/irb/helper.rb
  test/irb/test_context.rb
  test/irb/test_debug_cmd.rb
  test/irb/test_irb.rb
  test/irb/yamatanooroti/test_rendering.rb
Labels: enhancement
