Repository ruby/irb, pull requests merged in 2024-04, with the labels that each got.

#886 Allow defining custom commands in IRB
  lib/irb.rb
  lib/irb/command.rb
  lib/irb/command/edit.rb
  lib/irb/default_commands.rb
  test/irb/test_command.rb
Labels: enhancement

#927 Fix % escape in prompt format
  lib/irb.rb
  test/irb/test_context.rb
Labels: bug

#923 Remove exit command workaround, handle IRB_EXIT in debug_readline
  lib/irb.rb
  lib/irb/command/exit.rb
  lib/irb/command/force_exit.rb
  test/irb/command/test_force_exit.rb
  test/irb/test_debugger_integration.rb
Labels: bug

#624 Support helper method registration
  lib/irb/command/help.rb
  lib/irb/default_commands.rb
  lib/irb/helper_method.rb
  lib/irb/helper_method/base.rb
  lib/irb/helper_method/conf.rb
  lib/irb/workspace.rb
  test/irb/command/test_help.rb
  test/irb/test_helper_method.rb
Labels: enhancement

#933 Add EXTEND_IRB.md to introduce IRB's command and helper registration mechanism
  EXTEND_IRB.md
  README.md
Labels: documentation

#937 Restore MAIN_CONTEXT correctly
  lib/irb.rb
  test/irb/test_irb.rb
Labels: bug
