Repository ruby/irb, pull requests merged in 2024-08, with the labels that each got.

#984 Update COMPARED_WITH_PRY.md
  COMPARED_WITH_PRY.md
Labels: documentation

#987 Improve easter_egg logo resolution
  lib/irb/easter-egg.rb
  lib/irb/ruby_logo.aa
Labels: enhancement

#989 Fix kill pager pid throwing Errno::ESRCH when pager process already terminated
  lib/irb/pager.rb
Labels: bug

#983 Colorize command input
  lib/irb/input-method.rb
  test/irb/test_input_method.rb
Labels: bug
