Repository ruby/irb, pull requests merged in 2024-03, with the labels that each got.

#859 Allow loading multiple irb files
  lib/irb/command/irb_info.rb
  lib/irb/history.rb
  lib/irb/init.rb
  test/irb/test_command.rb
  test/irb/test_history.rb
  test/irb/test_init.rb
Labels: enhancement

#897 rdoc version lock is required
  irb.gemspec
Labels: bug

#890 Use markdown format for docs
  .gitignore
  Rakefile
  lib/irb.rb
  lib/irb/ext/multi-irb.rb
  lib/irb/help.rb
Labels: documentation

#901 Fix irb_history saved to current directory
  doc/irb/indexes.md
  lib/irb/command/irb_info.rb
  lib/irb/history.rb
  lib/irb/init.rb
  lib/irb/lc/error.rb
  lib/irb/lc/ja/error.rb
  test/irb/test_command.rb
  test/irb/test_history.rb
  test/irb/test_init.rb
  test/irb/yamatanooroti/test_rendering.rb
Labels: bug
