Repository ruby/irb, pull requests merged in 2024-05, with the labels that each got.

#917 Support `IRB.conf[:BACKTRACE_FILTER]`
  lib/irb.rb
  test/irb/helper.rb
  test/irb/test_irb.rb
Labels: enhancement

#939 Use the new GH pages site for documentation
  README.md
Labels: documentation

#940 Let IRB::Color.colorable? always return true|false
  lib/irb/color.rb
Labels: bug

#947 Use flag instead of caller for `debug`'s binding.irb check
  lib/irb.rb
  lib/irb/command/debug.rb
  lib/irb/context.rb
  test/irb/test_debugger_integration.rb
Labels: bug

#948 Improve help message for no meta commands
  lib/irb/command/base.rb
  lib/irb/command/help.rb
  test/irb/command/test_custom_command.rb
Labels: bug

#953 Add a new initialization step to validate IRB.conf's values
  lib/irb/context.rb
  lib/irb/init.rb
  test/irb/test_init.rb
Labels: bug

#956 Reorder ruby lex clauses for unrecoverable first
  lib/irb/ruby-lex.rb
Labels: bug
