Repository ruby/irb, pull requests merged in 2024-10, with the labels that each got.

#1007 Use correct binding in debug mode
  lib/irb/debug/ui.rb
  test/irb/test_debugger_integration.rb
Labels: bug

#1010 Change default completor from regexp to type-completor if RUBY_VERSION>=3.4
  lib/irb/context.rb
  lib/irb/init.rb
  test/irb/test_context.rb
  test/irb/test_init.rb
  test/irb/test_type_completor.rb
Labels: enhancement

#1015 Improve Debugging with IRB section to make it easier to get started
  README.md
Labels: documentation

#1018 Remove bignum check from save_history
  lib/irb/history.rb
Labels: bug

#988 Always use alternate sceen on alt-d
  lib/irb/easter-egg.rb
  lib/irb/input-method.rb
Labels: bug
