Repository ruby/irb, pull requests merged in 2024-12, with the labels that each got.

#1039 Don't show 'Maybe IRB bug!' in show_source and ls command
  lib/irb/command/ls.rb
  lib/irb/source_finder.rb
  test/irb/command/test_show_source.rb
  test/irb/test_command.rb
Labels: bug

#1043 Page the output in irb:rdbg sessions too
  lib/irb/debug/ui.rb
Labels: enhancement

#1046 Load history when starting a direct debug session
  lib/irb/debug.rb
  test/irb/test_history.rb
Labels: bug

#1047 Avoid generating documentation pages for internal components
  .document
  Rakefile
  lib/irb.rb
  lib/irb/command/base.rb
Labels: documentation

#1049 Fix broken rdoc-ref caused by a typo
  lib/irb.rb
Labels: documentation

#1054 Add `ri` an alias to the `show_doc` command
  lib/irb/default_commands.rb
  test/irb/test_command.rb
Labels: enhancement

#1053 Restructure IRB's documentation
  .document
  .github/workflows/gh-pages.yml
  .gitignore
  .rdoc_options
  Rakefile
  doc/.document
  doc/COMMAND_LINE_OPTIONS.md
  doc/COMPARED_WITH_PRY.md
  doc/Configurations.md
  doc/EXTEND_IRB.md
  doc/Index.md
  irb.gemspec
  lib/.document
  lib/irb.rb
  test/irb/yamatanooroti/test_rendering.rb
Labels: documentation

#1055 Use the documentation site as the source of truth
  EXTEND_IRB.md
  README.md
  irb.gemspec
Labels: documentation

#1057 Fix broken `history` command with `-g`
  lib/irb/command/history.rb
  test/irb/test_command.rb
Labels: bug
