Repository ruby/irb, pull requests merged in 2024-06, with the labels that each got.

#963 Remove useless Reline::Key.new and update wrong comment for alt+d
  lib/irb/input-method.rb
Labels: bug

#964 Add accidentally dropped disable_irb command back
  lib/irb/default_commands.rb
  test/irb/command/test_disable_irb.rb
Labels: bug

#965 Help users choose between helper methods and commands in the extension document
  EXTEND_IRB.md
Labels: documentation

#972 Stop echoing or storing command calls' `nil` return value
  lib/irb/context.rb
  lib/irb/statement.rb
  test/irb/test_command.rb
  test/irb/test_irb.rb
Labels: enhancement

#961 Allow assigning and using local variable name conflicting with command
  lib/irb.rb
  test/irb/command/test_custom_command.rb
Labels: bug
