Repository ruby/irb, pull requests merged in 2025-01, with the labels that each got.

#1056 Extract contributing guideline into a CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  doc/Index.md
Labels: documentation

#1061 Print more actionable message when the exception may be an IRB bug
  lib/irb.rb
Labels: bug

#1062 `IRB.conf[:SAVE_HISTORY]` should handle boolean values
  lib/irb/history.rb
  lib/irb/init.rb
  test/irb/test_history.rb
Labels: bug

#1063 [DOC] Remove unnecessary escape from completor class names
  doc/Index.md
Labels: documentation

#1065 Colorize backref token bold green like global variables
  lib/irb/color.rb
  test/irb/test_color.rb
Labels: bug

#1044 Add copy command
  doc/Configurations.md
  lib/irb/color_printer.rb
  lib/irb/command/copy.rb
  lib/irb/context.rb
  lib/irb/default_commands.rb
  lib/irb/init.rb
  lib/irb/inspector.rb
  man/irb.1
  test/irb/command/test_copy.rb
  test/irb/test_color_printer.rb
  test/irb/test_init.rb
Labels: enhancement

#1040 Show a quick preview of inspect result before pager launch
  lib/irb.rb
  lib/irb/command/copy.rb
  lib/irb/context.rb
  lib/irb/inspector.rb
  lib/irb/pager.rb
  test/irb/test_context.rb
  test/irb/test_pager.rb
  test/irb/yamatanooroti/test_rendering.rb
Labels: enhancement

#1067 [DOC] Update documentation about the new copy command
  doc/Index.md
  lib/irb/command/copy.rb
Labels: documentation

#1068 [DOC] Exclude the word `IRB` from RDoc's autolinking
  .rdoc_options
  Gemfile
  doc/COMMAND_LINE_OPTIONS.md
  doc/Configurations.md
  doc/Index.md
Labels: documentation

#1073 Zero winsize bugfix
  lib/irb/input-method.rb
  lib/irb/pager.rb
  test/irb/test_pager.rb
Labels: bug
